inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/application.rb"
    - "config/environments/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "lib/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false