version: 2.1
orbs:
  ruby: circleci/ruby@3.2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.2.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install